name: build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: ./gradlew publishToMavenLocal

      - uses: actions/upload-artifact@v4
        with:
          name: maven-local
          path: ~/.m2
          if-no-files-found: error

      - run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.3.11579264"

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install conan

      - run: ./gradlew assemble
        working-directory: tests/0_sample_library

      - run: ./gradlew assemble
        working-directory: tests/1_cmake_layout
