name: build
on: push

jobs:

  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        conan_version:
          - 2.5.0
          - 2.6.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: ./gradlew publishToMavenLocal

      - run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.3.11579264"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install conan==${{matrix.conan_version}}
      - run: conan --version

      - run: conan profile detect
        if: ${{ matrix.testcase != 'no_default_profile_installed' }}

      - run: conan profile list

      - run: conan remote add odr https://artifactory.opendocument.app/artifactory/api/conan/conan

      - run: ./gradlew assemble
        working-directory: tests/odrcore-user
