name: build
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        conan_version:
          - 2.5.0
          - 2.6.0
        serial_mode:
          - '--serial-mode'
          - ''
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install conan==${{matrix.conan_version}}
      - run: conan --version

      - run: conan profile detect

      - uses: actions/checkout@v4
      - run: python tests/parallel_conan_install/testcase.py ${{ matrix.serial_mode }}
